// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.F5os
{
    /// <summary>
    /// Resource to Manage network interfaces on F5OS systems like VELOS chassis partitions or rSeries platforms
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using F5os = Pulumi.F5os;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var testInterface = new F5os.Interface("test_interface", new()
    ///     {
    ///         Enabled = true,
    ///         Name = "1.0",
    ///         NativeVlan = 5,
    ///         TrunkVlans = new[]
    ///         {
    ///             1,
    ///             2,
    ///             3,
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Interface can be imported by specifying the Interface name
    /// 
    /// ```sh
    /// $ pulumi import f5os:index/interface:Interface test-import 1.0
    /// ```
    /// </summary>
    [F5osResourceType("f5os:index/interface:Interface")]
    public partial class Interface : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Enables or disables interface.
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// Name of the interface to configure.
        /// For VELOS partitions blade/port format is required e.g. `1/1.0`
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Configures the VLAN ID to associate with the interface.
        /// The `native_vlan` parameter is used for untagged traffic.
        /// </summary>
        [Output("nativeVlan")]
        public Output<int?> NativeVlan { get; private set; } = null!;

        /// <summary>
        /// Operational state of the interface.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// Configures multiple VLAN IDs to associate with the interface.
        /// The `trunk_vlans` parameter is used for tagged traffic
        /// </summary>
        [Output("trunkVlans")]
        public Output<ImmutableArray<int>> TrunkVlans { get; private set; } = null!;


        /// <summary>
        /// Create a Interface resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Interface(string name, InterfaceArgs? args = null, CustomResourceOptions? options = null)
            : base("f5os:index/interface:Interface", name, args ?? new InterfaceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Interface(string name, Input<string> id, InterfaceState? state = null, CustomResourceOptions? options = null)
            : base("f5os:index/interface:Interface", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Interface resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Interface Get(string name, Input<string> id, InterfaceState? state = null, CustomResourceOptions? options = null)
        {
            return new Interface(name, id, state, options);
        }
    }

    public sealed class InterfaceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enables or disables interface.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Name of the interface to configure.
        /// For VELOS partitions blade/port format is required e.g. `1/1.0`
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Configures the VLAN ID to associate with the interface.
        /// The `native_vlan` parameter is used for untagged traffic.
        /// </summary>
        [Input("nativeVlan")]
        public Input<int>? NativeVlan { get; set; }

        [Input("trunkVlans")]
        private InputList<int>? _trunkVlans;

        /// <summary>
        /// Configures multiple VLAN IDs to associate with the interface.
        /// The `trunk_vlans` parameter is used for tagged traffic
        /// </summary>
        public InputList<int> TrunkVlans
        {
            get => _trunkVlans ?? (_trunkVlans = new InputList<int>());
            set => _trunkVlans = value;
        }

        public InterfaceArgs()
        {
        }
        public static new InterfaceArgs Empty => new InterfaceArgs();
    }

    public sealed class InterfaceState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enables or disables interface.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Name of the interface to configure.
        /// For VELOS partitions blade/port format is required e.g. `1/1.0`
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Configures the VLAN ID to associate with the interface.
        /// The `native_vlan` parameter is used for untagged traffic.
        /// </summary>
        [Input("nativeVlan")]
        public Input<int>? NativeVlan { get; set; }

        /// <summary>
        /// Operational state of the interface.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("trunkVlans")]
        private InputList<int>? _trunkVlans;

        /// <summary>
        /// Configures multiple VLAN IDs to associate with the interface.
        /// The `trunk_vlans` parameter is used for tagged traffic
        /// </summary>
        public InputList<int> TrunkVlans
        {
            get => _trunkVlans ?? (_trunkVlans = new InputList<int>());
            set => _trunkVlans = value;
        }

        public InterfaceState()
        {
        }
        public static new InterfaceState Empty => new InterfaceState();
    }
}
