// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.F5os.Outputs
{

    [OutputType]
    public sealed class LoggingTls
    {
        /// <summary>
        /// TLS certificate for secure logging.
        /// </summary>
        public readonly string Certificate;
        /// <summary>
        /// TLS private key for secure logging (sensitive).
        /// </summary>
        public readonly string Key;

        [OutputConstructor]
        private LoggingTls(
            string certificate,

            string key)
        {
            Certificate = certificate;
            Key = key;
        }
    }
}
