// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.F5os.Outputs
{

    [OutputType]
    public sealed class LoggingServer
    {
        /// <summary>
        /// The IP address or hostname of the remote logging server.
        /// </summary>
        public readonly string Address;
        /// <summary>
        /// Whether authentication is enabled for TCP protocol.
        /// </summary>
        public readonly bool? Authentication;
        /// <summary>
        /// Log selectors for this server, specifying facility and severity.
        /// </summary>
        public readonly ImmutableArray<Outputs.LoggingServerLog> Logs;
        /// <summary>
        /// The port number for the remote logging server (1-65535).
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// The protocol used for logging (tcp or udp).
        /// </summary>
        public readonly string Protocol;

        [OutputConstructor]
        private LoggingServer(
            string address,

            bool? authentication,

            ImmutableArray<Outputs.LoggingServerLog> logs,

            int port,

            string protocol)
        {
            Address = address;
            Authentication = authentication;
            Logs = logs;
            Port = port;
            Protocol = protocol;
        }
    }
}
