// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.F5os.Outputs
{

    [OutputType]
    public sealed class LoggingRemoteForwarding
    {
        /// <summary>
        /// Whether remote forwarding is enabled.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// List of files for remote forwarding output.
        /// </summary>
        public readonly ImmutableArray<Outputs.LoggingRemoteForwardingFile> Files;
        /// <summary>
        /// Log selectors for remote forwarding, specifying facility and severity.
        /// </summary>
        public readonly ImmutableArray<Outputs.LoggingRemoteForwardingLog> Logs;

        [OutputConstructor]
        private LoggingRemoteForwarding(
            bool enabled,

            ImmutableArray<Outputs.LoggingRemoteForwardingFile> files,

            ImmutableArray<Outputs.LoggingRemoteForwardingLog> logs)
        {
            Enabled = enabled;
            Files = files;
            Logs = logs;
        }
    }
}
