// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.F5os.Outputs
{

    [OutputType]
    public sealed class LoggingCaBundle
    {
        /// <summary>
        /// The PEM-encoded content of the CA bundle.
        /// </summary>
        public readonly string Content;
        /// <summary>
        /// The name of the CA bundle.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private LoggingCaBundle(
            string content,

            string name)
        {
            Content = content;
            Name = name;
        }
    }
}
