# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('f5os')


class _ExportableConfig(types.ModuleType):
    @property
    def disable_tls_verify(self) -> Optional[bool]:
        """
        `disable_tls_verify` controls whether a client verifies the server's certificate chain and host name. default it is set
        to `true`. If `disable_tls_verify` is true, crypto/tls accepts any certificate presented by the server and any host name
        in that certificate. In this mode, TLS is susceptible to machine-in-the-middle attacks unless custom verification is
        used. can be provided by `DISABLE_TLS_VERIFY` environment variable. > **NOTE** If it is set to `false`, certificate/ca
        certificates should be added to `trusted store` of host where we are running this provider.
        """
        return __config__.get_bool('disableTlsVerify')

    @property
    def host(self) -> Optional[str]:
        """
        URI/Host details for F5os Device,can be provided via `F5OS_HOST` environment variable.
        """
        return __config__.get('host')

    @property
    def password(self) -> Optional[str]:
        """
        Password for F5os Device,can be provided via `F5OS_PASSWORD` environment variable.
        """
        return __config__.get('password')

    @property
    def port(self) -> Optional[int]:
        """
        Port Number to be used to make API calls to HOST
        """
        return __config__.get_int('port')

    @property
    def teem_disable(self) -> Optional[bool]:
        """
        If this flag set to true,sending telemetry data to TEEM will be disabled,can be provided via `TEEM_DISABLE` environment
        variable.
        """
        return __config__.get_bool('teemDisable')

    @property
    def username(self) -> Optional[str]:
        """
        Username for F5os Device,can be provided via `F5OS_USERNAME` environment variable.User provided here need to have
        required permission as per
        [UserManagement](https://techdocs.f5.com/en-us/f5os-a-1-4-0/f5-rseries-systems-administration-configuration/title-user-mgmt.html)
        """
        return __config__.get('username')

