// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package f5os

import (
	"context"
	"reflect"

	"errors"
	"github.com/BlackDark/pulumi-f5os/sdk/go/f5os/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Resource used to configure DNS settings (servers and domains) on F5OS systems (VELOS or rSeries).
//
// > **NOTE:** The `Dns` resource updates DNS servers and search domains on the F5OS platforms using Open API
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/BlackDark/pulumi-f5os/sdk/go/f5os"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Manages DNS servers and search domains on F5OS platforms
//			_, err := f5os.NewDns(ctx, "test", &f5os.DnsArgs{
//				DnsServers: pulumi.StringArray{
//					pulumi.String("8.8.8.8"),
//				},
//				DnsDomains: pulumi.StringArray{
//					pulumi.String("internal.domain"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type Dns struct {
	pulumi.CustomResourceState

	// List of DNS search domains. Example: `["internal.domain"]`
	DnsDomains pulumi.StringArrayOutput `pulumi:"dnsDomains"`
	// List of DNS server IP addresses. Example: `["8.8.8.8", "1.1.1.1"]`
	DnsServers pulumi.StringArrayOutput `pulumi:"dnsServers"`
}

// NewDns registers a new resource with the given unique name, arguments, and options.
func NewDns(ctx *pulumi.Context,
	name string, args *DnsArgs, opts ...pulumi.ResourceOption) (*Dns, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DnsServers == nil {
		return nil, errors.New("invalid value for required argument 'DnsServers'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Dns
	err := ctx.RegisterResource("f5os:index/dns:Dns", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDns gets an existing Dns resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDns(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DnsState, opts ...pulumi.ResourceOption) (*Dns, error) {
	var resource Dns
	err := ctx.ReadResource("f5os:index/dns:Dns", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Dns resources.
type dnsState struct {
	// List of DNS search domains. Example: `["internal.domain"]`
	DnsDomains []string `pulumi:"dnsDomains"`
	// List of DNS server IP addresses. Example: `["8.8.8.8", "1.1.1.1"]`
	DnsServers []string `pulumi:"dnsServers"`
}

type DnsState struct {
	// List of DNS search domains. Example: `["internal.domain"]`
	DnsDomains pulumi.StringArrayInput
	// List of DNS server IP addresses. Example: `["8.8.8.8", "1.1.1.1"]`
	DnsServers pulumi.StringArrayInput
}

func (DnsState) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsState)(nil)).Elem()
}

type dnsArgs struct {
	// List of DNS search domains. Example: `["internal.domain"]`
	DnsDomains []string `pulumi:"dnsDomains"`
	// List of DNS server IP addresses. Example: `["8.8.8.8", "1.1.1.1"]`
	DnsServers []string `pulumi:"dnsServers"`
}

// The set of arguments for constructing a Dns resource.
type DnsArgs struct {
	// List of DNS search domains. Example: `["internal.domain"]`
	DnsDomains pulumi.StringArrayInput
	// List of DNS server IP addresses. Example: `["8.8.8.8", "1.1.1.1"]`
	DnsServers pulumi.StringArrayInput
}

func (DnsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsArgs)(nil)).Elem()
}

type DnsInput interface {
	pulumi.Input

	ToDnsOutput() DnsOutput
	ToDnsOutputWithContext(ctx context.Context) DnsOutput
}

func (*Dns) ElementType() reflect.Type {
	return reflect.TypeOf((**Dns)(nil)).Elem()
}

func (i *Dns) ToDnsOutput() DnsOutput {
	return i.ToDnsOutputWithContext(context.Background())
}

func (i *Dns) ToDnsOutputWithContext(ctx context.Context) DnsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DnsOutput)
}

// DnsArrayInput is an input type that accepts DnsArray and DnsArrayOutput values.
// You can construct a concrete instance of `DnsArrayInput` via:
//
//	DnsArray{ DnsArgs{...} }
type DnsArrayInput interface {
	pulumi.Input

	ToDnsArrayOutput() DnsArrayOutput
	ToDnsArrayOutputWithContext(context.Context) DnsArrayOutput
}

type DnsArray []DnsInput

func (DnsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Dns)(nil)).Elem()
}

func (i DnsArray) ToDnsArrayOutput() DnsArrayOutput {
	return i.ToDnsArrayOutputWithContext(context.Background())
}

func (i DnsArray) ToDnsArrayOutputWithContext(ctx context.Context) DnsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DnsArrayOutput)
}

// DnsMapInput is an input type that accepts DnsMap and DnsMapOutput values.
// You can construct a concrete instance of `DnsMapInput` via:
//
//	DnsMap{ "key": DnsArgs{...} }
type DnsMapInput interface {
	pulumi.Input

	ToDnsMapOutput() DnsMapOutput
	ToDnsMapOutputWithContext(context.Context) DnsMapOutput
}

type DnsMap map[string]DnsInput

func (DnsMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Dns)(nil)).Elem()
}

func (i DnsMap) ToDnsMapOutput() DnsMapOutput {
	return i.ToDnsMapOutputWithContext(context.Background())
}

func (i DnsMap) ToDnsMapOutputWithContext(ctx context.Context) DnsMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DnsMapOutput)
}

type DnsOutput struct{ *pulumi.OutputState }

func (DnsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Dns)(nil)).Elem()
}

func (o DnsOutput) ToDnsOutput() DnsOutput {
	return o
}

func (o DnsOutput) ToDnsOutputWithContext(ctx context.Context) DnsOutput {
	return o
}

// List of DNS search domains. Example: `["internal.domain"]`
func (o DnsOutput) DnsDomains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Dns) pulumi.StringArrayOutput { return v.DnsDomains }).(pulumi.StringArrayOutput)
}

// List of DNS server IP addresses. Example: `["8.8.8.8", "1.1.1.1"]`
func (o DnsOutput) DnsServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Dns) pulumi.StringArrayOutput { return v.DnsServers }).(pulumi.StringArrayOutput)
}

type DnsArrayOutput struct{ *pulumi.OutputState }

func (DnsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Dns)(nil)).Elem()
}

func (o DnsArrayOutput) ToDnsArrayOutput() DnsArrayOutput {
	return o
}

func (o DnsArrayOutput) ToDnsArrayOutputWithContext(ctx context.Context) DnsArrayOutput {
	return o
}

func (o DnsArrayOutput) Index(i pulumi.IntInput) DnsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Dns {
		return vs[0].([]*Dns)[vs[1].(int)]
	}).(DnsOutput)
}

type DnsMapOutput struct{ *pulumi.OutputState }

func (DnsMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Dns)(nil)).Elem()
}

func (o DnsMapOutput) ToDnsMapOutput() DnsMapOutput {
	return o
}

func (o DnsMapOutput) ToDnsMapOutputWithContext(ctx context.Context) DnsMapOutput {
	return o
}

func (o DnsMapOutput) MapIndex(k pulumi.StringInput) DnsOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Dns {
		return vs[0].(map[string]*Dns)[vs[1].(string)]
	}).(DnsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DnsInput)(nil)).Elem(), &Dns{})
	pulumi.RegisterInputType(reflect.TypeOf((*DnsArrayInput)(nil)).Elem(), DnsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DnsMapInput)(nil)).Elem(), DnsMap{})
	pulumi.RegisterOutputType(DnsOutput{})
	pulumi.RegisterOutputType(DnsArrayOutput{})
	pulumi.RegisterOutputType(DnsMapOutput{})
}
