// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.F5os.Inputs
{

    public sealed class LoggingRemoteForwardingGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether remote forwarding is enabled.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        [Input("files")]
        private InputList<Inputs.LoggingRemoteForwardingFileGetArgs>? _files;

        /// <summary>
        /// List of files for remote forwarding output.
        /// </summary>
        public InputList<Inputs.LoggingRemoteForwardingFileGetArgs> Files
        {
            get => _files ?? (_files = new InputList<Inputs.LoggingRemoteForwardingFileGetArgs>());
            set => _files = value;
        }

        [Input("logs")]
        private InputList<Inputs.LoggingRemoteForwardingLogGetArgs>? _logs;

        /// <summary>
        /// Log selectors for remote forwarding, specifying facility and severity.
        /// </summary>
        public InputList<Inputs.LoggingRemoteForwardingLogGetArgs> Logs
        {
            get => _logs ?? (_logs = new InputList<Inputs.LoggingRemoteForwardingLogGetArgs>());
            set => _logs = value;
        }

        public LoggingRemoteForwardingGetArgs()
        {
        }
        public static new LoggingRemoteForwardingGetArgs Empty => new LoggingRemoteForwardingGetArgs();
    }
}
