// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Resource used to configure DNS settings (servers and domains) on F5OS systems (VELOS or rSeries).
 *
 * > **NOTE:** The `f5os.Dns` resource updates DNS servers and search domains on the F5OS platforms using Open API
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as f5os from "@pulumi/f5os";
 *
 * // Manages DNS servers and search domains on F5OS platforms
 * const test = new f5os.Dns("test", {
 *     dnsServers: ["8.8.8.8"],
 *     dnsDomains: ["internal.domain"],
 * });
 * ```
 */
export class Dns extends pulumi.CustomResource {
    /**
     * Get an existing Dns resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnsState, opts?: pulumi.CustomResourceOptions): Dns {
        return new Dns(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'f5os:index/dns:Dns';

    /**
     * Returns true if the given object is an instance of Dns.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Dns {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Dns.__pulumiType;
    }

    /**
     * List of DNS search domains. Example: `["internal.domain"]`
     */
    public readonly dnsDomains!: pulumi.Output<string[]>;
    /**
     * List of DNS server IP addresses. Example: `["8.8.8.8", "1.1.1.1"]`
     */
    public readonly dnsServers!: pulumi.Output<string[]>;

    /**
     * Create a Dns resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DnsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnsArgs | DnsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnsState | undefined;
            resourceInputs["dnsDomains"] = state ? state.dnsDomains : undefined;
            resourceInputs["dnsServers"] = state ? state.dnsServers : undefined;
        } else {
            const args = argsOrState as DnsArgs | undefined;
            if ((!args || args.dnsServers === undefined) && !opts.urn) {
                throw new Error("Missing required property 'dnsServers'");
            }
            resourceInputs["dnsDomains"] = args ? args.dnsDomains : undefined;
            resourceInputs["dnsServers"] = args ? args.dnsServers : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Dns.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Dns resources.
 */
export interface DnsState {
    /**
     * List of DNS search domains. Example: `["internal.domain"]`
     */
    dnsDomains?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of DNS server IP addresses. Example: `["8.8.8.8", "1.1.1.1"]`
     */
    dnsServers?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a Dns resource.
 */
export interface DnsArgs {
    /**
     * List of DNS search domains. Example: `["internal.domain"]`
     */
    dnsDomains?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of DNS server IP addresses. Example: `["8.8.8.8", "1.1.1.1"]`
     */
    dnsServers: pulumi.Input<pulumi.Input<string>[]>;
}
