// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Get Information about the various components of F5OS device. Currently the various components whose information is fetched are `interfaces`, `vlans`, `tenant images`, `controller images` and `partition images`. Information about partition and controller images can only be fetched from the Velos controller so please set you provider block to point to a Velos controller when you want information for partition and controller images
 */
export function getDeviceInfo(args: GetDeviceInfoArgs, opts?: pulumi.InvokeOptions): Promise<GetDeviceInfoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("f5os:index/getDeviceInfo:getDeviceInfo", {
        "gatherInfoOfs": args.gatherInfoOfs,
    }, opts);
}

/**
 * A collection of arguments for invoking getDeviceInfo.
 */
export interface GetDeviceInfoArgs {
    /**
     * List of components for which to gather information. This attribute accept the following values:
     * [`all`,`interfaces`,`vlans`,`tenantImages`,`partitionImages`,`controllerImages`,`!all`,`!interfaces`,`!vlans`,`!tenant_images`,`!partition_images`,`!controller_images`]
     */
    gatherInfoOfs: string[];
}

/**
 * A collection of values returned by getDeviceInfo.
 */
export interface GetDeviceInfoResult {
    /**
     * Information about existing controller images
     */
    readonly controllerImages: outputs.GetDeviceInfoControllerImage[];
    /**
     * List of components for which to gather information. This attribute accept the following values:
     * [`all`,`interfaces`,`vlans`,`tenantImages`,`partitionImages`,`controllerImages`,`!all`,`!interfaces`,`!vlans`,`!tenant_images`,`!partition_images`,`!controller_images`]
     */
    readonly gatherInfoOfs: string[];
    /**
     * Identifier for Device Info
     */
    readonly id: string;
    /**
     * Information about existing interfaces
     */
    readonly interfaces: outputs.GetDeviceInfoInterface[];
    /**
     * Device info
     */
    readonly partitionImages: outputs.GetDeviceInfoPartitionImage[];
    /**
     * Information about existing tenant images
     */
    readonly tenantImages: outputs.GetDeviceInfoTenantImage[];
    /**
     * Information about existing vlans
     */
    readonly vlans: outputs.GetDeviceInfoVlan[];
}
/**
 * Get Information about the various components of F5OS device. Currently the various components whose information is fetched are `interfaces`, `vlans`, `tenant images`, `controller images` and `partition images`. Information about partition and controller images can only be fetched from the Velos controller so please set you provider block to point to a Velos controller when you want information for partition and controller images
 */
export function getDeviceInfoOutput(args: GetDeviceInfoOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDeviceInfoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("f5os:index/getDeviceInfo:getDeviceInfo", {
        "gatherInfoOfs": args.gatherInfoOfs,
    }, opts);
}

/**
 * A collection of arguments for invoking getDeviceInfo.
 */
export interface GetDeviceInfoOutputArgs {
    /**
     * List of components for which to gather information. This attribute accept the following values:
     * [`all`,`interfaces`,`vlans`,`tenantImages`,`partitionImages`,`controllerImages`,`!all`,`!interfaces`,`!vlans`,`!tenant_images`,`!partition_images`,`!controller_images`]
     */
    gatherInfoOfs: pulumi.Input<pulumi.Input<string>[]>;
}
