// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Get information about the tenant Image on f5os platform.
 *
 * Use this data source to get information, whether image available on platform or not
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as f5os from "@pulumi/f5os";
 *
 * const test = f5os.getTenantImage({
 *     imageName: "BIGIP-17.1.0-0.0.16.ALL-F5OS.qcow2.zip.bundle",
 * });
 * ```
 */
export function getTenantImage(args: GetTenantImageArgs, opts?: pulumi.InvokeOptions): Promise<GetTenantImageResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("f5os:index/getTenantImage:getTenantImage", {
        "imageName": args.imageName,
    }, opts);
}

/**
 * A collection of arguments for invoking getTenantImage.
 */
export interface GetTenantImageArgs {
    /**
     * Name of the tenant image to check
     */
    imageName: string;
}

/**
 * A collection of values returned by getTenantImage.
 */
export interface GetTenantImageResult {
    /**
     * Unique identifier of this data source
     */
    readonly id: string;
    /**
     * Name of the tenant image to check
     */
    readonly imageName: string;
    /**
     * Status of Image on the F5OS Platforms
     */
    readonly imageStatus: string;
}
/**
 * Get information about the tenant Image on f5os platform.
 *
 * Use this data source to get information, whether image available on platform or not
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as f5os from "@pulumi/f5os";
 *
 * const test = f5os.getTenantImage({
 *     imageName: "BIGIP-17.1.0-0.0.16.ALL-F5OS.qcow2.zip.bundle",
 * });
 * ```
 */
export function getTenantImageOutput(args: GetTenantImageOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTenantImageResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("f5os:index/getTenantImage:getTenantImage", {
        "imageName": args.imageName,
    }, opts);
}

/**
 * A collection of arguments for invoking getTenantImage.
 */
export interface GetTenantImageOutputArgs {
    /**
     * Name of the tenant image to check
     */
    imageName: pulumi.Input<string>;
}
